// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"
import { Modal } from "tailwindcss-stimulus-components"
application.register('modal', Modal)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
